version: "3.7"

services:
  postgres:
    expose:
      - 5432

  alchemist:
    build:
      args:
        - ENVIRONMENT=dev
    environment:
      - AWS_ACCESS_KEY_ID=${ODC_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${ODC_SECRET_KEY}
    volumes:
      - .:/code
      - ./output:/tmp/alchemist
    depends_on:
      - postgres
