specification:
  product: ga_s2a_ard_nbar_granule
  measurements: ['nbar_green', 'nbar_red', 'nbar_nir_1', 'nbar_swir_2', 'nbar_swir_3']
  measurement_renames:
    nbar_green: green
    nbar_red: red
    nbar_nir_1: nir
    nbar_swir_2: swir1
    nbar_swir_3: swir2

  override_product_family: ard # The relationship of the source dataset to the newly derived dataset
  basis: nbar_green

  transform: fc.virtualproduct.FractionalCover
  transform_args:
    regression_coefficients:
      #  These coefficients are for Sentinel 2
      #  The coefficients is applied to band values in the 0-10,000 range, before it is scaled to a fraction
      #  This means the first coefficient has been also scaled when compared to the literature
      #  This is where I got the coefficients from
      #  https://github.com/GeoscienceAustralia/fc/blob/s2a-coefficients/config/s2_fc_albers.yaml
      blue:
        - -22.0
        - 0.9551
      green:
        - 31.0
        - 1.0582
      red:
        - 64.0
        - 0.9871
      nir:
        - 120.0
        - 1.0187
      swir1:
        - 79.0
        - 0.9528
      swir2:
        - -42.0
        - 0.9688

output:
  location: 's3://dea-sandbox-data-staging/fractional-cover/fc/v2.2.1'
  dtype: uint8 # single value for all bands
  nodata: 255 # single value for all bands
  preview_image: [bs, pv, npv]
  write_data_settings:
      overview_resampling: average
  metadata: # metadata are settings available on DatasetAssembler
    product_family: fractional_cover
    producer: ga.gov.au
    dataset_version: 2.2.1
  properties: # Properties can be anything and everything
    # dataset maturity must be nrt, interim or final
    dea:dataset_maturity: interim

processing:
  dask_chunks:
    x: 4000
    y: 4000
