name: Publish to PyPI

on:
  release:
    types: [published]

permissions: {}

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish_pypi:
    if: github.repository == 'opendatacube/datacube-alchemist'
    timeout-minutes: 35
    runs-on: ubuntu-latest
    # Permit authenticating to PyPI
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.8

      - name: Install Twine
        run: |
          python -m pip install --upgrade twine
          python -m pip freeze

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true
